language: python
python:
  - "2.7.15rc1"
install:
  - pip install -r requirements.txt
#Specify what command to run test
script:
  - pytest --cov
  - coverage
  - coverage3 report
  - coveralls 
after_success:
